config/routes.rb
Rails.application.routes.draw do

devise_for :users
get '/dashboard', to: 'users#dashboard'
post '/project/:id/resource/:user_id', to:'projectcodes#assignresource' ,as:'assign_resource_project'
delete '/deleteuser/:user_id/project/:id', to: 'projectcodes#removeuser', as: 'deleteuser_project'
get '/users/:user_id/addResource/:id', to: 'projectcodes#getallusers' ,as:'get_all_users'
post '/users/:user_id/project/:project_id/bugs/:id/assign_bug', to:'bugs#assignbugtodeveloper' ,as:'assign_project_developer_bug'
post '/users/:user_id/project/:projectcode_id/bugs/:id/mark_bug', to:'bugs#markasreolved' ,as:'mark_project_bug_resolved'
get '/users/:user_id/bugs',to:'bugs#showspecificbugs' ,as:'show_specific_bugs'
get '/users/:user_id/assigned_qa',to:'users#show_assigned_creators' ,as:'show_specific_creator'
get '/users/:user_id/assigned_developer',to:'users#show_assigned_developers' ,as:'show_specific_developer'
  resources :users,only:[] do
    resources :projectcodes , :path=>'projects' do
      resources :bugs
    end
  end
   

root to: 'users#dashboard'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  # def set_default_role
  #   self.type ||= :Manager
  # end  
  scope :get_user, -> id { find(id) if id.present? }
  scope :get_all_creators, -> project { project.users.where(type: "Creator")  }
  scope :get_all_developers, -> project { project.users.where(type: "Developer")  }
  scope :get_manager_projects, -> user { user.projectcodes  }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   
         has_many :userprojects
         has_many :projectcodes ,:through => :userprojects
 
    def self.get_all_developers_excluding_specificproject(project)
      User.all.where.not(id:project.users.ids,type:["Creator","Manager"])  
    end
   
    def self.get_all_creators_excluding_specificproject(project)
      User.all.where.not(id:project.users.ids,type:["Developer","Manager"])  
    end
     
    def self.get_assigned_creators(projects)
      User.joins(:projectcodes).where(projectcodes:{id: projects.all.ids }, type: "Creator").uniq
    end 
    def self.get_assigned_developers(projects)
      User.joins(:projectcodes).where(projectcodes:{id: projects.all.ids }, type: "Developer").uniq
    end      
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :get_data, only: [:show_assigned_creators, :show_assigned_developers]

    def dashboard
     @projects=current_user.projectcodes;
     if(current_user.type=="Manager")
       @totalprojectcreators=Userproject.get_total_creators(@projects)
       @totalprojectdevelopers=Userproject.get_total_developers(@projects)
     else 
          @totalbugs=current_user.bugs.count
     end   
    end

    def show_assigned_creators
      @creators=User.get_assigned_creators(@projects)
    end

    def show_assigned_developers
      @developers=User.get_assigned_developers(@projects)
    end

    def get_data
      @user=User.get_user(params[:user_id])
      @projects=User.get_manager_projects(@user)
    end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_creator.html.erb
<div class="col-md-6">
                <%= link_to user_projectcodes_path(current_user.id), action: 'go' do %>
        <div class="card">
                <%= image_tag("project.svg", alt:"Total projects created", class: "card-img-top") %>
                <div class="card-body">
                        <h4 class="card-title">Total projects involved</h4>
                        <p class="card-text"><%= @projects.count  %></p>
                </div>
        </div>
        <% end %>
</div>
<div class="col-md-6">
                <%= link_to show_specific_bugs_path(current_user.id), action: 'go' do %>   
        <div class="card">
                <%= image_tag("bug-solid.svg", alt:"Total projects created", class: "card-img-top") %>
                <div class="card-body">
                        <h4 class="card-title">Total Bugs Reported</h4>
                        <p class="card-text"><%=  @totalbugs %></p>
                </div>
        </div>
        <% end %>
</div>

app/views/users/_developer.html.erb
<div class="col-md-6">
<%= link_to user_projectcodes_path(current_user.id), action: 'go' do %>
        <div class="card">
                <%= image_tag("project.svg", alt: "Total projects created", class: "card-img-top") %>
                <div class="card-body">
                        <h4 class="card-title">Total projects involved</h4>
                        <p class="card-text"><%= @projects.count  %></p>
                </div>
        </div>

<% end %>
</div>
<div class="col-md-6">
 <%= link_to show_specific_bugs_path(current_user.id), :action => 'go' do %>        
        <div class="card">
                <%= image_tag("bug-solid.svg", alt: "Total Bugs involved", class: "card-img-top") %>
                <div class="card-body">
                        <h4 class="card-title">Total Bugs involved</h4>
                        <p class="card-text"><%=  @totalbugs %></p>
                </div>
        </div>
  <% end %>      
</div>

app/views/users/_manager.html.erb
<div class="col-md-4">
      <%= link_to user_projectcodes_path(current_user.id), action: 'go' do %>
           <div class="card">
                <%= image_tag("project.svg", alt: "Total projects created", class: "card-img-top") %>
                    <div class="card-body">
                          <h4 class="card-title">Total projects created</h4>
                              <p class="card-text"><%= @projects.count  %></p>
                    </div>
          </div>
      <% end %>
</div>


<div class="col-md-4">
    <%= link_to  show_specific_creator_path(current_user.id), action: 'go' do %>
      <div class="card">
            <%= image_tag("user-solid.svg", alt: "Total projects created", class: "card-img-top") %>
              <div class="card-body">
                  <h4 class="card-title">Total QA assigned</h4>
                      <p class="card-text"><%=  @totalprojectcreators %></p>
              </div>
      </div>
    <% end %>
</div>
<div class="col-md-4">
    <%= link_to  show_specific_developer_path(current_user.id), action: 'go' do %>
  <div class="card">
    <%= image_tag("developers.svg", alt: "Total projects created", class: "card-img-top") %>
    <div class="card-body">
      <h4 class="card-title">Total developers assigned</h4>
      <p class="card-text"><%= @totalprojectdevelopers  %></p>
    </div>
  </div>
  <% end %>
</div>

app/views/users/dashboard.html.erb
<div class="middlecontent">
      <div class="jumbotron">
            <h1>Dashboard</h1>
      </div>
            <div class="container fullcontainer">
                  <div class="row">
                        <% if(current_user.type=="Manager") %>
                              <%= render 'manager' %>
                        <% elsif(current_user.type=="Creator") %>
                              <%= render 'creator' %>
                        <% else %>
                              <%= render 'developer' %>
                        <% end %>
                  </div>
            </div>
</div>

app/views/users/show_assigned_creators.html.erb
<div class="middlecontent">
        <div class="jumbotron">
          <h1>All QA List </h1>
        </div>
        <div class="container">
          <div class="row">
            <div class="col-md-12">
                <h3 class="tableheading">QA</h3>
              <%= render partial: "projectcodes/table",locals: {resource: @creators} %>
            </div>
            
          </div>
        </div>
        <div>
        </div>

app/views/users/show_assigned_developers.html.erb
<div class="middlecontent">
        <div class="jumbotron">
          <h1>All Developer List </h1>
        </div>
        <div class="container">
          <div class="row">
            <div class="col-md-12">
                <h3 class="tableheading">Developers</h3>
              <%= render partial: "projectcodes/table",locals: {resource: @developers} %>
            </div>
            
          </div>
        </div>
        <div>
        </div>

app/views/users/showassignedcreators.html.erb
<div class="middlecontent">
        <div class="jumbotron">
          <h1>All QA List </h1>
        </div>
        <div class="container">
          <div class="row">
            <div class="col-md-12">
                <h3 class="tableheading">QA</h3>
              <%= render partial: "projectcodes/table",locals: {resource: @creators} %>
            </div>
            
          </div>
        </div>
        <div>
        </div>

app/views/users/showassigneddevelopers.html.erb
<div class="middlecontent">
        <div class="jumbotron">
          <h1>All Developer List </h1>
        </div>
        <div class="container">
          <div class="row">
            <div class="col-md-12">
                <h3 class="tableheading">Developers</h3>
              <%= render partial: "projectcodes/table",locals: {resource: @developers} %>
            </div>
            
          </div>
        </div>
        <div>
        </div>