config/routes.rb
Rails.application.routes.draw do

devise_for :users
get '/dashboard', to: 'users#dashboard'
post '/project/:id/resource/:user_id', to:'projectcodes#assignresource' ,as:'assign_resource_project'
delete '/deleteuser/:user_id/project/:id', to: 'projectcodes#removeuser', as: 'deleteuser_project'
get '/users/:user_id/addResource/:id', to: 'projectcodes#getallusers' ,as:'get_all_users'
post '/users/:user_id/project/:project_id/bugs/:id/assign_bug', to:'bugs#assignbugtodeveloper' ,as:'assign_project_developer_bug'
post '/users/:user_id/project/:projectcode_id/bugs/:id/mark_bug', to:'bugs#markasreolved' ,as:'mark_project_bug_resolved'
get '/users/:user_id/bugs',to:'bugs#showspecificbugs' ,as:'show_specific_bugs'
get '/users/:user_id/assigned_qa',to:'users#show_assigned_creators' ,as:'show_specific_creator'
get '/users/:user_id/assigned_developer',to:'users#show_assigned_developers' ,as:'show_specific_developer'
  resources :users,only:[] do
    resources :projectcodes , :path=>'projects' do
      resources :bugs
    end
  end
   

root to: 'users#dashboard'
end

app/models/projectcode.rb
class Projectcode < ApplicationRecord
    before_save :set_default_value
    
    validates :name, presence: true, uniqueness: true
    
    has_many :bugs, dependent: :destroy
    has_many :userprojects, dependent: :destroy
    has_many :users, :through => :userprojects
    belongs_to :manager
    
    scope :get_project, -> id { find(id) if id.present? }
  
    def set_default_value
      if self.name.blank?
          self.name=nil
      end   
    end
 

end

app/controllers/projectcodes_controller.rb
class ProjectcodesController < ApplicationController
  
    before_action :set_user, only: [:index, :assignresource, :new, :edit]
    before_action :authorize_user, only: [:index, :new]
    
		before_action :set_project, except: [:index , :new , :create]
		before_action :authorize_project, except: [:index, :new, :create, :edit]
    
    def index
      @allprojects = current_user.projectcodes
    end  

    def new
      @project= Projectcode.new
    end
   
    def show
      @creators= User.get_all_creators(@project)
      @developers= User.get_all_developers(@project)
    end   
    
    def create       
			@project= Projectcode.new(name: post_params[:name], manager_id: current_user.id);
	
			authorize @project

			if @project.save
				redirect_to user_projectcodes_path(current_user.id)
			else 
					render 'new'
			end 
    end   
    
    def edit
    end

    def update
      if(@project.update(post_params))
        redirect_to user_projectcode_path(params[:user_id] , @project)
      else
          render 'edit'  
      end
    end

    def destroy 
      @project.destroy
      respond_to do |format|
        format.js { render layout: false}
      end
    end

    def removeuser
      Userproject.get_project_user(params[:user_id]).destroy
      redirect_to user_projectcode_path(params[:user_id] , @project)
    end

    def getallusers
			@developers= User.get_all_developers_excluding_specificproject(@project)
			@creators= User.get_all_creators_excluding_specificproject(@project)
    end
  
    
    def assignresource
      @userproject= Userproject.new(user_id: @user.id, projectcode_id: params[:id], usertype: @user.type)
        
      if @userproject.save
          redirect_to user_projectcode_path(@user, params[:id])
      else
          render 'getallusers'
      end
    end 
     
    private
    
    def set_user
      @user= User.get_user(params[:user_id])
    end

    def set_project
      @project= Projectcode.get_project(params[:id])
    end 
    def authorize_project
      authorize @project
    end 
    
    def authorize_user
      authorize @user
    end   

    def post_params
      params.require(:projectcode).permit(:name)
    end
 
  end

app/helpers/projectcodes_helper.rb
module ProjectcodesHelper
end

app/views/projectcodes/_error.html.erb
<% resource.errors.each do |attr, msg| %>
<li>
  <%= resource.errors.full_messages_for(attr).first if resource.errors[attr].first == msg %>
</li>
<% end %>

app/views/projectcodes/_form.html.erb
<div class="middlecontent">
    <% if controller.action_name == "new" %>
        <div class="jumbotron">
            <h1> Create Project</h1>
        </div>
  <% else %>
          <div class="jumbotron">
            <h1> Edit Project</h1>
          </div>
  <% end %>
  <%= form_for  [User, @project] do |f| %>
  <%= render "bugs/error",resource:@project %>
  <div class="form-group row">
      <div class="help-block with-errors"></div>
        <%= f.label :name ,class:"col-sm-2 col-form-label" %> <br>
          <div class="col-sm-8">
              <%= f.text_field :name ,class:"form-control my-form",required: true %>
          </div>
  </div>
  <% if controller.action_name == "new" %>
        <%= f.button 'Create Project', type: 'submit',class:"btb btn-primary" %>
  <% else %>
          <%= f.button 'Edit Project', type: 'submit',class:"btb btn-primary" %>
  <% end %>

  <% end %>
</div>

app/views/projectcodes/_table.html.erb
<table class="table table-hover table-dark full-table">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Email</th>
            <th scope="col"> Name</th>
            <% if controller.action_name=="show"||controller.action_name=="getallusers" %>
            <th scope="col">Actions</th>
            <% end %>
        </tr>
    </thead>
    <tbody>
        <% resource.each do |resource| %>
        <tr>
            <th scope="row"><%=resource.id%></th>
            <td><%= resource.email %></td>
            <td><%= resource.name %></td>
           <% if controller.action_name == "show" %>
            <td>
                <%= link_to 'Delete', deleteuser_project_path(resource.id,@project.id), method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-danger delete" %></td>  
           <% elsif controller.action_name == "getallusers" %>
                <td><%= link_to 'Add Resource', assign_resource_project_path(@project,resource),method: :post,class:"btn btn-primary" %>
           <% end %>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/projectcodes/destroy.js.erb
$('.delete').bind('ajax:success',function(){
$(this).closest('tr').fadeOut(()=>{alert("your project is successfuly deleted")});
})

app/views/projectcodes/edit.html.erb
<%= render 'form'  %>

app/views/projectcodes/getallusers.html.erb
<div class="middlecontent">
  <div class="jumbotron">
      <h1>Add Resorces for <%=@project.name %>'s </h1>
  </div>
  <div class="container">
      <div class="row">
          <div class="col-md-6">
              <h3 class="tableheading">QA</h3>
                  <%= render partial: "table",locals: {resource: @creators} %>
          </div>
              <div class="col-md-6">
                  <h3 class="tableheading">Developer</h3>
                     <%= render partial: "table",locals: {resource: @developers} %>
              </div>
        </div>
  </div>
  <div>
  </div>

app/views/projectcodes/index.html.erb
<div class="middlecontent">
    <div class="jumbotron">
        <h1>All Projects</h1>
    </div>
  <% if @allprojects.count>0 %>
  		<div id="list of all projects">
    			<table class="table table-hover table-dark full-table">
      			<thead>
        			<tr>
          			<th scope="col">Id</th>
          			<th scope="col">Title</th>
          				<% if current_user.type=="Manager" %>
          							<th scope="col"></th>
          				<% end %>
          			<th scope="col" colspan="2" class="tabledata">Actions</th>
        			</tr>
      			</thead>

      <tbody>
        	<% @allprojects.each do |project| %>
        		<tr>
          			<th scope="row"><%=project.id%></th>
          			<td><%= project.name %></td>
          					<% if(current_user.type == "Manager")  %>
          									<td><%= link_to 'Add Resources', get_all_users_path(project.manager_id, project), class: "btn btn-primary" %></td>
          									<td><%= link_to 'Edit', edit_user_projectcode_path(project.manager_id, project), class: "btn btn-primary" %></td>
          									<td>
            										<%= link_to 'Delete', user_projectcode_path(project.manager_id, project), method: :delete, data: { confirm: 'Are you sure?', disable_with: "Destroying", remote: true},class:"btn btn-danger delete" %>
          									<td><%= link_to 'Show', user_projectcode_path(project.manager_id, project), class: "btn btn-success" %></td>
          					<% elsif(current_user.type=="Developer") %>
          										<td class="tabledata">
            										<%= link_to 'View Bugs', user_projectcode_bugs_path(current_user.id, project), class: "btn btn-primary"%></td>
          					<% else %>
          											<td class="tabledata">
            										<%= link_to 'View Bugs', user_projectcode_bugs_path(current_user.id , project), class: "btn btn-primary"%></td>
          											<td class="tabledata">
            										<%= link_to 'Report Bug', new_user_projectcode_bug_path(current_user.id, project), class: "btn btn-primary" %>
          											</td>
        		</tr>
        						<% end %>
        <% end %>
      </tbody>
    </table>
  </div>
  <% end %>
</div>

app/views/projectcodes/new.html.erb
<%= render 'form'  %>

app/views/projectcodes/new.js.erb
console.log("error occur")...

app/views/projectcodes/removeuser.js.erb
$('.delete').bind('ajax:success',function(){
$(this).closest('tr').fadeOut(()=>{alert("your resource is successfuly deleted")});
})

app/views/projectcodes/show.html.erb
<div class="middlecontent">
    <div class="jumbotron">
        <h1><%=@project.name %>'s Resources</h1>
    </div>
  
    <div class="container">
         <div class="row">
            <div class="col-md-6">
              <h3 class="tableheading">QA</h3>
                <%= render partial: "table",locals: {resource: @creators} %>
            </div>
            <div class="col-md-6">
                <h3 class="tableheading">Developer</h3>
                  <%= render partial: "table",locals: {resource: @developers} %>
            </div>
        </div>
   </div>
</div>