config/routes.rb
Rails.application.routes.draw do

devise_for :users
get '/dashboard', to: 'users#dashboard'
post '/project/:id/resource/:user_id', to:'projectcodes#assignresource' ,as:'assign_resource_project'
delete '/deleteuser/:user_id/project/:id', to: 'projectcodes#removeuser', as: 'deleteuser_project'
get '/users/:user_id/addResource/:id', to: 'projectcodes#getallusers' ,as:'get_all_users'
post '/users/:user_id/project/:project_id/bugs/:id/assign_bug', to:'bugs#assignbugtodeveloper' ,as:'assign_project_developer_bug'
post '/users/:user_id/project/:projectcode_id/bugs/:id/mark_bug', to:'bugs#markasreolved' ,as:'mark_project_bug_resolved'
get '/users/:user_id/bugs',to:'bugs#showspecificbugs' ,as:'show_specific_bugs'
get '/users/:user_id/assigned_qa',to:'users#show_assigned_creators' ,as:'show_specific_creator'
get '/users/:user_id/assigned_developer',to:'users#show_assigned_developers' ,as:'show_specific_developer'
  resources :users,only:[] do
    resources :projectcodes , :path=>'projects' do
      resources :bugs
    end
  end
   

root to: 'users#dashboard'
end

app/models/bug.rb
class Bug < ApplicationRecord
  include AASM
  
  enum status: {
    newer: 0,
    started: 1,
    completed: 2,
    resolved: 3
   } 
   
    aasm column: :status, enum: true, whiny_tansitions: false do
     state :newer, initial: true
     state :started
     state :completed
     state :resolved

     event :set_next_state do
       transitions from: :newer , to: :started
     
       transitions from: :started, to: :completed, guard: :feature?
     
       transitions from: :started, to: :resolved, guard: :bug?
     end
   end  
   
    before_create :set_default_value
    
    validates :bugtype, presence: true 
    validates :title, presence: true, uniqueness: true   
    
    
    attr_accessor :screenshot
    mount_uploader :screenshot,ImageUploader
    
    belongs_to :creator
    belongs_to :projectcode
    
    
    scope :get_bug, -> id { find(id) if id.present? }
    scope :get_specificproject_bugs, -> id { where(projectcode_id: id) if id.present? }

    def set_default_value
      self.status="newer"   
    end  
    
    def self.get_specificuser_bugs(user)
      @bugs=user.bugs
    end  
    
    def setbug(id)
      update(developer_id:id)
    end 
    
   def feature?
      bugtype == "feature"
   end

   def bug?
      bugtype == "bug"
   end

 end  
 

app/controllers/bugs_controller.rb
    class BugsController < ApplicationController
    before_action :set_user, only: [:index, :edit, :new, :showspecificbugs]
    before_action :authorize_user, only: [:index, :showspecificbugs]
    
    before_action :set_project, only: [:index, :new]
    before_action :authorize_project, only: [:index]

    before_action :set_bug, only: [:markasreolved, :update, :destroy, :assignbugtodeveloper, :edit]
    before_action :authorize_bug, only: [:edit, :update, :destroy]

    def index
      @bugs=Bug.get_specificproject_bugs(params[:projectcode_id])
    end
   
    def new 
      @bug=Bug.new
    end

    def create
      @bug=Bug.create(post_params)
      if @bug.errors.count==0
          redirect_to user_projectcode_bugs_path
      else
            render 'new'
      end
    end

    def update
      if(@bug.update(post_params))
          redirect_to user_projectcode_bugs_path  
      else 
            render 'edit'
      end
    end
     
    def edit
      
    end

    def destroy
      @bug.destroy 
      respond_to do |format|
        format.js
      end
    end
    
    def markasreolved
      @bug.set_next_state!  
      redirect_to user_projectcode_bugs_path
    end  
    
    def assignbugtodeveloper
      @bug.setbug(params[:user_id])
      @bug.set_next_state!
      redirect_to user_projectcode_bugs_path(params[:user_id], @bug.projectcode_id)
    end
  
    def showspecificbugs
      @bugs=Bug.get_specificuser_bugs(@user)
    end  

    private
    def post_params
      params.require(:bug).permit(:title, :descryption, :screenshot, :deadline).
      merge(projectcode_id: params[:projectcode_id], creator_id: params[:user_id], date: Date.today, bugtype: params[:bugtype],status: params[:bugstatus] );
    end
    
    def set_project
      @project=Projectcode.get_project(params[:projectcode_id])
    end 

    def authorize_user
      authorize @user
    end
    
    def authorize_project
      authorize @project
    end 
    
    def set_user
      @user= User.get_user(params[:user_id])
    end  
    def set_bug
      @bug=Bug.get_bug(params[:id])
    end  
    
    def authorize_bug
      authorize @bug
    end


end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/views/bugs/_error.html.erb
<% if(resource.errors.any?) %>
    <div id="error_explanation">
    <% resource.errors.each do |attr, msg| %>
        <li>
          <%= resource.errors.full_messages_for(attr).first if resource.errors[attr].first == msg %>
        </li>
      <% end %>
    </div>
<% end %>

app/views/bugs/_showbug.html.erb
<tr>
  <td> <%= bug.title  %> </td>
  <td> <%= bug.bugtype  %> </td>
  <td> <%= bug.status %> </td>
  <td>  <%= image_tag(bug.screenshot, alt: "rss feed", class: "showbugimage zoom") %>  </td>
  <td> <%= bug.deadline %> </td>
  <td> <%= bug.projectcode.name %> </td>
  <% if data == "newer" %>
          <% if(current_user.type=="Creator") %>
              
              <td class="tabledata">
                        <%= link_to 'Edit', edit_user_projectcode_bug_path(bug.creator_id,bug.projectcode_id,bug),class:"btn btn-primary" %>
                  <%= link_to 'Delete', user_projectcode_bug_path(bug.creator_id,bug.projectcode_id,bug),method: :delete, data: { confirm: 'Are you sure?',remote: true },class:"btn btn-danger delete" %>
                  
             </td>
          <% elsif(current_user.type=="Developer")%>
              <td class="tabledata">
                <%= link_to 'Assign Bug', assign_project_developer_bug_path(current_user.id,bug.projectcode_id,bug),method: :post,class:"btn btn-primary" %>
               
              </td>
          <% end%>

  <% else %>
        <% if(current_user.type=="Creator") %>
              <td class="tabledata">
                <%= link_to 'Edit', edit_user_projectcode_bug_path(bug.creator_id,bug.projectcode_id,bug),class:"btn btn-primary" %>
              
            </td>
        <% elsif(current_user.type=="Developer") %>
                
                <td class="tabledata" id="change status">
                    <% if bug.bugtype=="bug" %>
                          <% if bug.status!="resolved" %>
                                <%= link_to 'Mark as resolved', mark_project_bug_resolved_path(current_user.id,bug.projectcode_id,bug),class:"btn btn-primary",method: :post %>
                          <% else %>
                                <%= link_to 'Mark as resolved', mark_project_bug_resolved_path(current_user.id,bug.projectcode_id,bug),class:"btn btn-primary disabled disablebutton",method: :post %>
                          <% end %>
                    <% else %>
                          <% if bug.status!="completed" %>
                                <%= link_to 'Mark as completed', mark_project_bug_resolved_path(current_user.id,bug.projectcode_id,bug),class:"btn btn-primary ",method: :post %>
                                
                          <% else %>
                                <%= link_to 'Mark as completed', mark_project_bug_resolved_path(current_user.id,bug.projectcode_id,bug),class:"btn btn-primary disabled disablebutton",method: :post %>
                          <% end %>
                    <% end %>
                        
                </td>
        <%end%>
  <%end%>

app/views/bugs/_table.html.erb
<table class="table table-hover table-dark full-table">
    <thead>
        <tr>
            <th scope="col">BugTitle</th>       
            <th scope="col">BugType</th>
            <th scope="col">BugStatus</th>
            <th scope="col">BugImage</th>
            <th scope="col">BugDeadline</th>
            <th scope="col">ProjectName</th>
            <th scope="col" colspan="2" class="tabledata">Actions</th>
        </tr>
    </thead>

    <tbody>
        <%if(data=="unassigned")%>
            <%resources.each do |bug| %>
                <% if bug.status=="newer" %>
                    <%= render partial: "showbug",locals: {bug: bug,data:"newer"} %>
                <% end %>
            <%end%>
        <%else%>
            <%resources.each do |bug| %>
                <%if bug.status=="started" ||bug.status=="completed" ||bug.status=="resolved"%>
                    <%= render partial: "showbug",locals: {bug: bug,data:"assigned"} %>
                <%end%>
            <%end%>
        <%end%>
    </tbody>
</table>

app/views/bugs/create.html.erb
<h1>Bugs#create</h1>
<p>Find me in app/views/bugs/create.html.erb</p>

app/views/bugs/destroy.html.erb
<h1>Bugs#destroy</h1>
<p>Find me in app/views/bugs/destroy.html.erb</p>

app/views/bugs/destroy.js.erb
$('.delete').bind('ajax:success',function(){
$(this).closest('tr').fadeOut(()=>{alert("Your Bug was successfuly deleted")});
})

app/views/bugs/edit.html.erb
<div class="middlecontent" >
  <div class="jumbotron">
      <h1>Edit Bug</h1>
  </div>
     <%= render "error",resource:@bug %>
     <%= form_with model: @bug, url:user_projectcode_bug_path ,:html =>{:multipart=>true}  do |f| %>

      <div class="form-group row">
          <div class="help-block with-errors"></div>
          <%= f.label :title ,class:"col-sm-2 col-form-label-special" %> <br>
              <div class="col-sm-8">
                <%= f.text_field :title ,class:"form-control my-form",required: true %> 
  
              </div>
      </div>
    <div class="form-group row">
        <div class="help-block with-errors"></div>
          <%= f.label :descryption ,class:"col-sm-2 col-form-label" %> <br>
              <div class="col-sm-8">
                <%= f.text_field :descryption ,class:"form-control my-form",required: true %> 
              </div>
    </div>

    <div class="form-group row">
          <div class="help-block with-errors"></div>
            <%= f.label :bugtype ,class:"col-sm-2 col-form-label"%> <br>
      <div class="col-sm-8">
            <%= select_tag(:bugtype, options_for_select([['feature','feature'],['Bug','bug']]),class:"form-control my-form") %>
    
      </div>
    </div>
      <div class="form-group row">
            <div class="help-block with-errors"></div>
               <%= f.label :bugstatus ,class:"col-sm-2 col-form-label"%> <br>
              <div class="col-sm-8">
                <%= select_tag(:bugstatus, options_for_select([['new','newer'],['started','started'],['completed','completed']]),class:"form-control my-form") %>
              </div>
      </div>   

        <div class="form-group row">
            <div class="help-block with-errors"></div>
                <%= f.label :deadline ,class:"col-sm-2 col-form-label"%> <br>
                <div class="col-sm-8">
                    <%= f.date_field :deadline, :class => "form-control my-form",required:true ,min: Date.today%>
                </div>
        </div> 

          <div class="form-group row">
              <div class="help-block with-errors"></div>
                  <%= f.label :screenshot ,class:"col-sm-2 col-form-label"%> <br>
                  <div class="col-sm-8">
                      <%= f.file_field :screenshot ,required: true,class:"form-control my-form file_field"%>
                  </div>
          </div> 
      <%= f.submit class: 'btn btn-primary' %>
      <% end  %>
</div>

app/views/bugs/index.html.erb
  <div class="middlecontent">
    <div id="list of all unassigned bugs">
      <div class="jumbotron">
        <h1>Unassigned bugs</h1>
      </div>
      <%= render partial: "table",locals: {resources: @bugs,data:'unassigned'} %>

    </div>


    <div id="list of all bugs" style="margin-top:50px">
      <div class="jumbotron">
        <h1>Assigned bugs</h1>
      </div>
      <%= render partial: "table",locals: {resources: @bugs,data:'assigned'} %>
    </div>
  </div>

app/views/bugs/new.html.erb
<div class="middlecontent">
  <div class="jumbotron">
      <h1>Create Bug</h1>
  </div>

  <%= form_for :bug, url: {action: "create"},:html =>{:multipart=>true} do |f| %>
  <%= render "error",resource:@bug %>
<div class="form-group row">
      <%= f.label :title ,class:"col-sm-2 col-form-label" %> <br>
    <div class="col-sm-8">
        <%= f.text_field :title ,class:"form-control my-form",required: true %>
    </div>
</div>

<div class="form-group row">
      <div class="help-block with-errors"></div>
            <%= f.label :descryption ,class:"col-sm-2 col-form-label" %> <br>
        <div class="col-sm-8">
            <%= f.text_field :descryption ,class:"form-control my-form",required: true %>
        </div>
</div>

<div class="form-group row">
    <div class="help-block with-errors"></div>
        <%= f.label :bugtype ,class:"col-sm-2 col-form-label"%> <br>
          <div class="col-sm-8">
              <%= select_tag(:bugtype, options_for_select([['feature','feature'],['Bug','bug']]),class:"form-control my-form") %>
          </div>
</div>

<div class="form-group row">
     <div class="help-block with-errors"></div>
        <%= f.label :bugstatus ,class:"col-sm-2 col-form-label"%> <br>
          <div class="col-sm-8">
            <%= select_tag(:bugstatus, options_for_select([['new','newer'],['started','started'],['completed','completed']]),class:"form-control my-form")%>
          </div>
</div>

<div class="form-group row">
      <div class="help-block with-errors"></div>
        <%= f.label :deadline ,class:"col-sm-2 col-form-label"%> <br>
          <div class="col-sm-8">
            <%= f.date_field :deadline, :class => "form-control my-form",required:true ,min: Date.today %>
          </div>
</div>

  <div class="form-group row">
        <%= f.label :screenshot ,class:"col-sm-2 col-form-label"%> <br>
      <div class="col-sm-8">
        <%= f.file_field :screenshot ,required: true,class:"form-control my-form file_field",id:"choose"%>
      </div>
  </div>
    <%= f.submit class: 'btn btn-primary' %>
    <% end %>
</div>

app/views/bugs/show.html.erb
<h1>Bugs#show</h1>
<p>Find me in app/views/bugs/show.html.erb</p>

app/views/bugs/showspecificbugs.html.erb
<div class="middlecontent">
    <div id="list of all unassigned bugs">
      <div class="jumbotron">
        <h1>Unassigned bugs</h1>
      </div>
      <%= render partial: "table",locals: {resources: @bugs,data:'unassigned'} %>

    </div>
    <div id="list of all bugs" style="margin-top:50px">
      <div class="jumbotron">
        <h1>Assigned bugs</h1>
      </div>
      <%= render partial: "table",locals: {resources: @bugs,data:'assigned'} %>
    </div>
  </div>

app/views/bugs/update.html.erb
<h1>Bugs#update</h1>
<p>Find me in app/views/bugs/update.html.erb</p>