config/routes.rb
Rails.application.routes.draw do

devise_for :users
get '/dashboard', to: 'users#dashboard'
post '/project/:id/resource/:user_id', to:'projectcodes#assignresource' ,as:'assign_resource_project'
delete '/deleteuser/:user_id/project/:id', to: 'projectcodes#removeuser', as: 'deleteuser_project'
get '/users/:user_id/addResource/:id', to: 'projectcodes#getallusers' ,as:'get_all_users'
post '/users/:user_id/project/:project_id/bugs/:id/assign_bug', to:'bugs#assignbugtodeveloper' ,as:'assign_project_developer_bug'
post '/users/:user_id/project/:projectcode_id/bugs/:id/mark_bug', to:'bugs#markasreolved' ,as:'mark_project_bug_resolved'
get '/users/:user_id/bugs',to:'bugs#showspecificbugs' ,as:'show_specific_bugs'
get '/users/:user_id/assigned_qa',to:'users#show_assigned_creators' ,as:'show_specific_creator'
get '/users/:user_id/assigned_developer',to:'users#show_assigned_developers' ,as:'show_specific_developer'
  resources :users,only:[] do
    resources :projectcodes , :path=>'projects' do
      resources :bugs
    end
  end
   

root to: 'users#dashboard'
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-light  nav-complete">
  <a class="navbar-brand" href="#">
  <%= image_tag("navimage.png", alt: "rss feed", class: "d-inline-block align-top nav-image") %>
  <h8>  Bugzilla </h8>
  </a>
  <span class="navbar-text">
  <% if user_signed_in? %>
      <%= link_to 'Log out', destroy_user_session_path, method: :delete ,class: "btn btn-danger btn-lg log-button"  %>
  <% end %>
</span>
</nav>

app/views/layouts/_sidebar.html.erb
<div class="w3-sidebar w3-bar-block w3-light-grey w3-card fullsidebar">
<div class="w3-sidebar w3-bar-block w3-large" style="background-color:bisque">
<div class="usertypename"><%= current_user.type %></div>    
<div class="sidebar-options">
<div class="sidebar-link">
        <%= image_tag("chalkboard-solid.svg", alt: "rss feed", class: "icon-small") %>
        
    <%= link_to 'Dashboard', dashboard_path ,class:"my-button"%>
</div>
<%  if(current_user.type=="Manager")  %> 
<div class="sidebar-link"> 
        <%= image_tag("tasks-solid.svg", alt: "rss feed", class: "icon-small") %>   
<%= link_to 'Showprojects', user_projectcodes_path(current_user.id) ,class:" my-button"%>
</div>
<div class="sidebar-link">
        <%= image_tag("plus-solid.svg", alt: "rss feed", class: "icon-small") %>
<%= link_to 'Createproject', new_user_projectcode_path(current_user.id) ,class:"my-button "%>
</div>
<% elsif(current_user.type=="Developer")  %>
<div class="sidebar-link">
        <%= image_tag("tasks-solid.svg", alt: "rss feed", class: "icon-small") %>
<%= link_to 'Showprojects', user_projectcodes_path(current_user.id) ,class:"my-button"%>
</div>

<% else %>
<div class="sidebar-link">
        <%= image_tag("tasks-solid.svg", alt: "rss feed", class: "icon-small") %>
<%= link_to 'Showprojects', user_projectcodes_path(current_user.id),class:"my-button" %>
</div>
<% end %>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Project</title>
  <%= csrf_meta_tags %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
    integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>

<body>
  <% if user_signed_in? %>
  <%=render 'layouts/navbar' %>
  <% end %>
  <div class="fluid-container">
    <div class="row">
      <div class="col-2">
        <% if user_signed_in? %>
        <%=render 'layouts/sidebar' %>
        <% end %>
      </div>
      <% if user_signed_in? %>
      <div class="col-10 middlesection">
        <% else %>
        <div class="col-12 middlesection"></div>
        <% end %>
        <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </div>
    </div>
</body>

</html>